name: Lint JavaScript

on:
  push:
    branches: [black-box-exercises]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npx eslint blackbox/hello.js
